# Generated by Django 4.0.1 on 2022-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nubank_id', models.UUIDField(unique=True)),
                ('destination_account', models.CharField(blank=True, max_length=256, null=True)),
                ('origin_account', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detail', models.TextField()),
                ('post_date', models.DateField()),
                ('title', models.CharField(max_length=128)),
                ('gql_typename', models.CharField(choices=[('TransferOutEvent', 'TransferOutEvent'), ('BillPaymentEvent', 'BillPaymentEvent'), ('BarcodePaymentEvent', 'BarcodePaymentEvent'), ('PixTransferOutEvent', 'PixTransferOutEvent'), ('TransferOutReversalEvent', 'TransferOutReversalEvent'), ('TransferInEvent', 'TransferInEvent'), ('DebitPurchaseEvent', 'DebitPurchaseEvent'), ('DebitWithdrawalFeeEvent', 'DebitWithdrawalFeeEvent'), ('DebitWithdrawalEvent', 'DebitWithdrawalEvent')], max_length=64, verbose_name='Statement Type')),
            ],
        ),
        migrations.CreateModel(
            name='CardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nubank_id', models.UUIDField()),
                ('account', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_without_iof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('details', models.JSONField()),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=128)),
                ('tokenized', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
