# Generated by Django 4.0.1 on 2022-02-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubank_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatement',
            name='gql_typename',
            field=models.CharField(choices=[('TransferOutEvent', 'TransferOutEvent'), ('BillPaymentEvent', 'BillPaymentEvent'), ('BarcodePaymentEvent', 'BarcodePaymentEvent'), ('PixTransferOutEvent', 'PixTransferOutEvent'), ('TransferOutReversalEvent', 'TransferOutReversalEvent'), ('TransferInEvent', 'TransferInEvent'), ('RemoveFromReserveEvent', 'RemoveFromReserveEvent'), ('AddToReserveEvent', 'AddToReserveEvent'), ('DebitPurchaseEvent', 'DebitPurchaseEvent'), ('DebitWithdrawalFeeEvent', 'DebitWithdrawalFeeEvent'), ('DebitWithdrawalEvent', 'DebitWithdrawalEvent')], max_length=64, verbose_name='Statement Type'),
        ),
    ]
